# Site settings
title: bryanculver.com
email: me@bryanculver.com
description: >
    The random tinkerings of today's MacGyver.
baseurl: ""
url: "http://bryanculver.com"
twitter_username: bryanculver
github_username:  bryanculver

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

gems:
  - jekyll-assets

assets:
  compress:
    css: true
    js: true
  prefix: "/assets"
  digest: true

babel_js_extensions: 'es6, babel, jsx'

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Bryan Culver"
resume_title:                   "Serial Technologist"
resume_contact_email:
  "me@bryanculver.com"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/bryanculver"
  resume_twitter_url:           "http://twitter.com/bryanculver"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/bryanculver"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://bryanculver.com"
  resume_keybase_url:           "https://keybase.io/bryanculver"

# Design settings
resume_theme:                   default

destination: public

exclude:
  - Gemfile
  - Gemfile.lock
  - /tmp/
  - config.ru

